### ISSUE TITLE
Problema de estilização na página de Login

### ISSUE THREAD

**Issue by FelipeSantos-cco** [GrayCloudTransaction/GreyCloudTransactions#3]
## Pág de login:
![image](https://github.com/GrayCloudTransaction/GreyCloudTransactions/assets/125617308/d7fb72bf-08cf-4c41-8125-e85e8fee16b1)

## Exemplo da pág de Cadastro 
![image](https://github.com/GrayCloudTransaction/GreyCloudTransactions/assets/125617308/b509ebfa-4f49-4771-be50-ac690568a781)

**Comment by giomenezes** [comment]
Arrumada com sucesso
