### ISSUE TITLE
Erro no login ao voltar da dash

### ISSUE THREAD

**Issue by giomenezes** [GrayCloudTransaction/GreyCloudTransactions#5]
O alerta de erro ao tentar logar acontece automaticamente quando você desloga da dash, tem que ta vendo o que está causando isso.

**Comment by FelipeSantos-cco** [comment]
## Bug Corrigido

Na função `manterConectado()` do arquivo `login.js` estava sendo chamado assim que a página de login era carregada.
![image](https://github.com/GrayCloudTransaction/GreyCloudTransactions/assets/125617308/120f9767-8957-4587-b5de-9f02ef2521ab)

Como é uma função que a sua implementação por si só já não estava funcionando, foi retirada para evitar problemas maiores até a 2° Sprint.

Commit: https://github.com/GrayCloudTransaction/GreyCloudTransactions/commit/1bda1eacde534975931fdd6c7ac9582b1e68f52a
